import Foundation

// Note: In a real project, this is generated by UniFFI
// and we would bridge to the C-API correctly.
// For the sake of this mock scaffold, we define dummy functions here.

public func init_flux(_ dataDir: String) -> Bool {
    // Calls into rust library
    return true
}

public func send_message(_ json: String) -> String {
    // Calls into rust library
    return "{}"
}
